apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: gaas-portal
  namespace: gaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaas-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gaas-portal
    spec:
      containers:
      - image: registry.npf.dk/gaas-portal
        imagePullPolicy: Always
        name: gaas-portal
        ports:
        - containerPort: 80
          protocol: TCP
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: gaas-portal
  namespace: gaas
spec:
  selector:
    app: gaas-portal
  type: ClusterIP
  clusterIP: 10.96.10.11
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
